title: Blake Drumm - Tech Blog
email: blakedrumm@microsoft.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the personal technical blog for Blake Drumm.
  Currently primarly focused towards Microsoft System Center Enterprise Management Products.
  I am an Microsoft Support Engineer on the System Center North America Support Team.
  
  © 2021 Blake Drumm
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blakedrumm.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  blakedrumm
linkedin_username: blakedrumm
facebook_username: blake.drumm
theme: minima
plugins:
  - jekyll-feed
  - jekyll-js-minify-plugin
