title: Blake Drumm - Tech Blog
email: blakedrumm@microsoft.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the personal technicial blog for Blake Drumm.
  Currently primarly focused towards System Center Enterprise Management Products.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blakedrumm.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  v-bldrum
theme: minima
plugins:
  - jekyll-feed
  - jekyll-js-minify-plugin
