# This is a basic workflow to help you get started with Actions

name: Copy Files to Remote File Repository

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
    build:
      name: Copy Files to Blake Drumm - File Repository
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - name: Copy Operations Manager Powershell to Blake Drumm - File Repository
        # You may pin to the exact commit or the version.
        # uses: AbleLincoln/push-to-sftp@a6c117bb60fdc94ab8e5b139cdb0b19bea582c81
        uses: AbleLincoln/push-to-sftp@v1.2
        with:
          # SFTP server
          host: ${{ secrets.HOST }}
          # SFTP server port
          port: ${{ secrets.PORT }}
          # SFTP username
          username: ${{ secrets.USERNAME }}
          # SFTP password
          password: ${{ secrets.PASSWORD }}
          # Source directory to upload from (will upload all files in this directory)
          sourceDir: "/github/workspace/Powershell"
          # Remote directory to upload to (WARNING: overwrites ALL files in this directory)
          targetDir: "/var/www/blakedrumm_fileshare/Powershell/OperationsManager/Single Files"
          
      - name: Copy AutomatedLab Powershell to Blake Drumm - File Repository
        # You may pin to the exact commit or the version.
        # uses: AbleLincoln/push-to-sftp@a6c117bb60fdc94ab8e5b139cdb0b19bea582c81
        uses: AbleLincoln/push-to-sftp@v1.2
        with:
          # SFTP server
          host: ${{ secrets.HOST }}
          # SFTP server port
          port: ${{ secrets.PORT }}
          # SFTP username
          username: ${{ secrets.USERNAME }}
          # SFTP password
          password: ${{ secrets.PASSWORD }}
          # Source directory to upload from (will upload all files in this directory)
          sourceDir: "/github/workspace/AutomatedLab"
          # Remote directory to upload to (WARNING: overwrites ALL files in this directory)
          targetDir: "/var/www/blakedrumm_fileshare/Powershell/AutomatedLab/OperationsManager"
          
          
      - name: Copy Operations Manager SQL Queries to Blake Drumm - File Repository
        # You may pin to the exact commit or the version.
        # uses: AbleLincoln/push-to-sftp@a6c117bb60fdc94ab8e5b139cdb0b19bea582c81
        uses: AbleLincoln/push-to-sftp@v1.2
        with:
          # SFTP server
          host: ${{ secrets.HOST }}
          # SFTP server port
          port: ${{ secrets.PORT }}
          # SFTP username
          username: ${{ secrets.USERNAME }}
          # SFTP password
          password: ${{ secrets.PASSWORD }}
          # Source directory to upload from (will upload all files in this directory)
          sourceDir: "/github/workspace/SQL Queries"
          # Remote directory to upload to (WARNING: overwrites ALL files in this directory)
          targetDir: "/var/www/blakedrumm_fileshare/SQL-Queries/OperationsManager"
