# This is a basic workflow to help you get started with Actions

name: Copy Files to Remote File Repository

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
    build:
      name: Copy Files to Blake Drumm - File Repository
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master

      - name: Copy Operations Manager Powershell to Blake Drumm - File Repository
        uses: fifsky/ssh-action@master
        with:
          command: ${{ secrets.SCRIPT_BODY }}
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          pass: ${{ secrets.PASSWORD }}
